repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: name-tests-test

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        args: [--quiet]

  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.9.3
  #   hooks:
  #   -   id: isort

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        args:
        - --max-line-length=500
        - --ignore-imports=yes
        - --disable=E1101
        - --disable=E0401
        - --disable=C0114
        - --disable=W0621
        - --disable=R0201
        - --disable=W0613
        - --disable=W0102
        - --disable=W0622
        - --disable=R1710
        - --disable=E0402
        - --disable=R1704
        - --disable=R0903 #had to disable it because of the serializers.py file
