name: Noticeboard Dev Deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [development]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull Repo on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zc_plugin_noticeboard
            git stash
            git checkout development
            git pull
            cd /var/www/zc_plugin_noticeboard/frontend
            yarn install
            yarn build
            cd /var/www/zc_plugin_noticeboard/backend/notice_project
            source bin/activate
            pip install -r requirements.txt
            python3 manage.py collectstatic --noinput
            pkill -u ${{secrets.USERNAME}} gunicorn 
            gunicorn --bind 0.0.0.0:8800 noticeboard.wsgi --daemon
